config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'schedule/index'

  root to: 'stocks#index'
  resources :stocks do
    post 'generate_chart', on: :collection
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern

  module ClassMethods
    def filter(filtering_params)
      results = self.where(nil)
      filtering_params.each do |key, value|
        results = results.public_send(key, value) if value.present?
      end
      results
    end
  end
end

app/models/stock.rb
class Stock < ApplicationRecord
  def set_chart(stock)
    chart_url = {}
    if stock.key?(:stock_1)
      chart_url['chart_1'] = IextradingService.new.charts(stock)
    elsif stock.key?(:stock_2)
      chart_url['chart_2'] = IextradingService.new.charts(stock)
    else
      chart_url['chart_3'] = IextradingService.new.charts(stock)
    end
    update!(chart_url)
    self
  end

  def columns_map(stock)
    {
      stock_id: stock['id'],
      chart_1: stock['chart_1'],
      chart_2: stock['chart_2'],
      chart_3: stock['chart_3'],
      cuit: stock['cuit']
    }
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/stocks_controller.rb
# frozen_string_literal: true

class StocksController < ApplicationController
  def index
    @stock = Stock.find_or_initialize_by(id: '1')
  end

  def new
    @stock = Stock.new
  end

  def create; end

  def show; end

  def edit; end

  def update
    if @stock.update(stock_params)
      redirect_to @stock
    else
      render 'edit'
    end
  end

  def destroy; end

  def generate_chart
    @stock = Stock.find_or_initialize_by(id: '1').set_chart(params)
    render 'index'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InterviewProject</title>
    <%= csrf_meta_tags %>
    <meta charset="UTF-8">
    <meta name=viewport content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-light bg-red">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><img src="<%= image_url('iex-app-icon.png')%>" alt=""></a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul style="width: 85rem; margin-top: -2%;" class="nav navbar-nav navbar-right">
            <li class="nav-item">
              <a class="nav-link" style="margin-left: 80%; width: 100%;" href="<%= stocks_path %>">Stock Charts <span class="sr-only">(current)</span></a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container" style="display: flex; justify-content: space-around;">
      <% flash.each do |key, message| %>
        <div class="alert alert-<%= key %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <footer>
    </footer>
  </body>
</html>

app/views/stocks/index.html.erb
<div style='display:inline-block'>
  <div class="search-table">
    <%= form_tag(generate_chart_stocks_path, method: :post, :class => 'search-form') do %>
      <%= text_area_tag :stock_1, params[:stock_1], class: 'search' %>
      <%= button_tag(type: "submit", class: "btn btn-default") do %>
        Search <i class="icon-repeat"></i>
      <% end %>
    <% end %>
  </div>

  <% if @stock.chart_1.present? %>
    <img src="<%= @stock.chart_1 -%>" style="width: auto; height: 200px; display: block;margin-top: 5%;">
  <% end %>
</div>

<div style='display:inline-block'>
  <div class="search-table">
    <%= form_tag(generate_chart_stocks_path, method: :post, :class => 'search-form') do %>
      <%= text_area_tag :stock_2, params[:stock_2], class: 'search' %>
      <%= button_tag(type: "submit", class: "btn btn-default") do %>
        Search <i class="icon-repeat"></i>
      <% end %>
    <% end %>
  </div>
  <% if @stock.chart_2.present? %>
    <img src="<%= @stock.chart_2 -%>" style="width: auto; height: 200px; display: block;margin-top: 5%;">
  <% end %>
</div>

<div style='display:inline-block'>
  <div class="search-table">
    <%= form_tag(generate_chart_stocks_path, method: :post, :class => 'search-form') do %>
      <%= text_area_tag :stock_3, params[:stock_3], class: 'search' %>
      <%= button_tag(type: "submit", class: "btn btn-default") do %>
        Search <i class="icon-repeat"></i>
      <% end %>
    <% end %>
  </div>

  <% if @stock.chart_3.present? %>
    <img src="<%= @stock.chart_3 -%>" style="width: auto; height: 200px; display: block;margin-top: 5%;">
  <% end %>
</div>